name: staff
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  go_router: ^13.0.0
  shared_preferences: ^2.2.1
  http: ^1.1.0
  fluttertoast: ^8.0.8
  flutter_native_splash : ^2.3.7
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.2.0
  dio: ^5.4.0
  provider: ^6.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/res/images/staff_logo.png"
  adaptive_icon_background: "#FFFAF1FD"
  adaptive_icon_foreground: "lib/res/images/staff_logo.png"
  
  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - lib/res/images/staff_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
